### ISSUE TITLE
During canister install token : Invalid data: Unable to serialize Candid values: wrong number of argument values

### ISSUE THREAD

**Issue by harshnambiar** [Psychedelic/DIP20#27]
While trying to run the create token commands, this error shows up.

Way to Replicate Error:
cd rust
dfx canister create --all
dfx build
dfx canister install token --argument="(\"data:image/jpeg;base64,...\", \"DFinance Coin\", \"DFC\", 8, 10000000000000000, principal \"qk36l-k7g7k-mtr6a-bfuek-eqsah-yjjj7-jurfe-54jjj7-jurfe-554sq-d7qhw-jw3su-jqe\", 10000)"
Invalid data: Unable to serialize Candid values: wrong number of argument values

**Comment by ozwaldorf** [comment]
Hi @harshnambiar ! Currently reviewing a pretty decent refractor (https://github.com/Psychedelic/DIP20/tree/feat/tooling) that should address these changes, and provides some tooling to test and deploy your token. The changes should be merged in today!
